apiVersion: apps/v1
kind: Deployment
metadata:
  name: roman-numeral-convertor
  labels:
    app: roman-numeral-convertor
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: roman-numeral-convertor
  template:
    metadata:
      labels:
        app: roman-numeral-convertor
    spec:
      serviceAccountName: roman-numeral-convertor
      securityContext:
        runAsNonRoot: true
      containers:
        - name: service
          image: ewocker/roman-numeral-convertor:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"
          securityContext:
            runAsUser: 65532
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["all"]
          env:
            - name: NODE_ENV
              value: kubernetes

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: roman-numeral-convertor
  name: roman-numeral-convertor
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app: roman-numeral-convertor
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: roman-numeral-convertor
  name: roman-numeral-convertor
